#### Intr To Python

In [1]:
print('fit a model with', 11, 'variables')

fit a model with 11 variables


In [4]:
print?

Signature: print(*args, sep=' ', end='\n', file=None, flush=False)
Docstring:
Prints the values to a stream, or to sys.stdout by default.

sep
  string inserted between values, default a space.
end
  string appended after the last value, default a newline.
file
  a file-like object (stream); defaults to the current sys.stdout.
flush
  whether to forcibly flush the stream.
Type:      builtin_function_or_method

In [5]:
3+5

8

In [6]:
"hello" + " " + "world"

'hello world'

In [7]:
x = [3, 4, 5]
x

[3, 4, 5]

In [8]:
y = [4, 9, 7]
x+y

[3, 4, 5, 4, 9, 7]

In [9]:
import numpy as np

In [11]:
x = np.array([3, 4, 5])
y = np.array([4, 9, 7])

In [12]:
x+y

array([ 7, 13, 12])

In [13]:
x = np.array([[1, 2], [3, 4]])
x

array([[1, 2],
       [3, 4]])

In [14]:
x.ndim

2

In [15]:
x.dtype

dtype('int64')

In [16]:
np.array([[1, 2], [3.0, 4]]).dtype

dtype('float64')

In [17]:
np.array?

Docstring:
array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
      like=None)

Create an array.

Parameters
----------
object : array_like
    An array, any object exposing the array interface, an object whose
    ``__array__`` method returns an array, or any (nested) sequence.
    If object is a scalar, a 0-dimensional array containing object is
    returned.
dtype : data-type, optional
    The desired data-type for the array. If not given, NumPy will try to use
    a default ``dtype`` that can represent the values (by applying promotion
    rules when necessary.)
copy : bool, optional
    If ``True`` (default), then the array data is copied. If ``None``,
    a copy will only be made if ``__array__`` returns a copy, if obj is
    a nested sequence, or if a copy is needed to satisfy any of the other
    requirements (``dtype``, ``order``, etc.). Note that any copy of
    the data is shallow, i.e., for arrays with object dtype, the new
    array will point to the 

In [18]:
np.array([[1, 2], [3, 4]], float).dtype

dtype('float64')

In [19]:
x.shape

(2, 2)

In [20]:
x = np.array([1, 2, 3, 4])
x.sum()

np.int64(10)

In [21]:
x = np.array([1, 2, 3, 4])
np.sum(x)

np.int64(10)

In [22]:
x = np.array([1, 2, 3, 4, 5, 6])
print('beginning x:\n', x)
x_reshape = x.reshape((2, 3))
print('reshaped x:\n', x_reshape)

beginning x:
 [1 2 3 4 5 6]
reshaped x:
 [[1 2 3]
 [4 5 6]]


In [23]:
x_reshape[0, 0]

np.int64(1)

In [24]:
x_reshape[1, 2]

np.int64(6)

In [25]:
print('x before we modify x_reshape:\n', x)
print('x_reshape before we modify x_reshape:\n', x_reshape)
x_reshape[0, 0] = 5
print('x_reshape after we modify its top left element:\n',
x_reshape)
print('x after we modify top left element of x_reshape:\n', x)

x before we modify x_reshape:
 [1 2 3 4 5 6]
x_reshape before we modify x_reshape:
 [[1 2 3]
 [4 5 6]]
x_reshape after we modify its top left element:
 [[5 2 3]
 [4 5 6]]
x after we modify top left element of x_reshape:
 [5 2 3 4 5 6]


In [26]:
my_tuple = (3, 4, 5)
my_tuple[0] = 2

TypeError: 'tuple' object does not support item assignment

In [ ]:
x_reshape.shape, x_reshape.ndim, x_reshape.T

In [ ]:
np.sqrt(x)

In [ ]:
x**2

In [ ]:
x**0.5

In [ ]:
x = np.random.normal(size=50)
x

In [ ]:
y = x + np.random.normal(loc=50, scale=1, size=50)

In [ ]:
np.corrcoef(x, y)

In [ ]:
print(np.random.normal(scale=5, size=2))
print(np.random.normal(scale=5, size=2))

In [ ]:
rng = np.random.default_rng(1303)
print(rng.normal(scale=5, size=2))
rng2 = np.random.default_rng(1303)
print(rng2.normal(scale=5, size=2))

In [ ]:
rng = np.random.default_rng(3)
y = rng.standard_normal(10)
np.mean(y), y.mean()

In [ ]:
np.var(y), y.var(), np.mean((y - y.mean())**2)

In [ ]:
np.sqrt(np.var(y)), np.std(y)

In [ ]:
X = rng.standard_normal((10, 3))
X

In [ ]:
X.mean(axis=0)

In [ ]:
X.mean(0)

In [ ]:
from matplotlib.pyplot import subplots
fig, ax = subplots(figsize=(8, 8))
x = rng.standard_normal(100)
y = rng.standard_normal(100)
ax.plot(x, y);

In [ ]:
output = subplots(figsize=(8, 8))
fig = output[0]
ax = output[1]

In [ ]:
fig, ax = subplots(figsize=(8, 8))
ax.plot(x, y, 'o');

In [ ]:
fig, ax = subplots(figsize=(8, 8))
ax.scatter(x, y, marker='o');

In [ ]:
fig, ax = subplots(figsize=(8, 8))
ax.scatter(x, y, marker='o')

In [ ]:
fig, ax = subplots(figsize=(8, 8)) .set_title()
ax.scatter(x, y, marker='o')
ax.set_xlabel("this is the x-axis")
ax.set_ylabel("this is the y-axis")
ax.set_title("Plot of X vs Y");

In [ ]:
fig.set_size_inches(12,3)
fig

In [ ]:
fig, axes = subplots(nrows=2,
ncols=3,
figsize=(15, 5))

In [ ]:
axes[0,1].plot(x, y, 'o')
axes[1,2].scatter(x, y, marker='+')
fig

In [ ]:
fig.savefig("Figure.png", dpi=400)
fig.savefig("Figure.pdf", dpi=200);

In [ ]:
axes[0,1].set_xlim([-1,1])
fig.savefig("Figure_updated.jpg")
fig

In [2]:
fig, ax = subplots(figsize=(8, 8))
x = np.linspace(-np.pi, np.pi, 50)
y=x
f = np.multiply.outer(np.cos(y), 1 / (1 + x**2))
ax.contour(x, y, f);

NameError: name 'subplots' is not defined

In [ ]:
fig, ax = subplots(figsize=(8, 8))
ax.contour(x, y, f, levels=45);

In [ ]:
fig, ax = subplots(figsize=(8, 8))
ax.imshow(f);

In [ ]:
seq1 = np.linspace(0, 10, 11)
seq1

In [ ]:
seq2 = np.arange(0, 10)
seq2

In [ ]:
"hello world"[3:6]

In [ ]:
"hello world"[slice(3,6)]

In [ ]:
A = np.array(np.arange(16)).reshape((4, 4))
A

In [ ]:
A[1,2]

In [ ]:
A[[1,3]]

In [ ]:
A[:,[0,2]]

In [ ]:
A[[1,3],[0,2]]

In [ ]:
np.array([A[1,0],A[3,2]])

In [ ]:
A[[1,3],[0,2,3]]

In [ ]:
A[[1,3]][:,[0,2]]

In [ ]:
idx = np.ix_([1,3],[0,2,3])
A[idx]

In [ ]:
A[1:4:2,0:3:2]

In [ ]:
keep_rows = np.zeros(A.shape[0], bool)
keep_rows

In [ ]:
keep_rows[[1,3]] = True
keep_rows

In [ ]:
np.all(keep_rows == np.array([0,1,0,1]))

In [ ]:
A[np.array([0,1,0,1])]

In [ ]:
A[keep_rows]

In [ ]:
keep_cols = np.zeros(A.shape[1], bool)
keep_cols[[0, 2, 3]] = True
idx_bool = np.ix_(keep_rows, keep_cols)
A[idx_bool]

In [ ]:
idx_mixed = np.ix_([1,3], keep_cols)
A[idx_mixed]

In [ ]:
import pandas as pd
Auto = pd.read_csv('Auto.csv')
Auto

In [ ]:
Auto = pd.read_csv('Auto.data', delim_whitespace=True)

In [ ]:
Auto['horsepower']

In [ ]:
np.unique(Auto['horsepower'])

In [ ]:
Auto = pd.read_csv('Auto.data',
na_values=['?'],
delim_whitespace=True)
Auto['horsepower'].sum()

In [ ]:
Auto.shape

In [ ]:
Auto_new = Auto.dropna()
Auto_new.shape

In [ ]:
Auto = Auto_new # overwrite the previous value
Auto.columns

In [ ]:
Auto[:3]

In [ ]:
idx_80 = Auto['year'] > 80
Auto[idx_80]

In [ ]:
Auto[['mpg', 'horsepower']]

In [ ]:
Auto.index

In [ ]:
Auto_re = Auto.set_index('name')
Auto_re

In [ ]:
Auto_re.columns

In [ ]:
rows = ['amc rebel sst', 'ford torino']
Auto_re.loc[rows]

In [ ]:
Auto_re.iloc[[3,4]]

In [ ]:
Auto_re.iloc[:,[0,2,3]]

In [ ]:
Auto_re.iloc[[3,4],[0,2,3]]

In [ ]:
Auto_re.loc['ford galaxie 500', ['mpg', 'origin']]

In [ ]:
idx_80 = Auto_re['year'] > 80
Auto_re.loc[idx_80, ['weight', 'origin']]

In [ ]:
Auto_re.loc[lambda df: df['year'] > 80, ['weight', 'origin']]

In [ ]:
Auto_re.loc[lambda df: (df['year'] > 80) & (df['mpg'] > 30),
['weight', 'origin']
]

In [ ]:
Auto_re.loc[lambda df: (df['displacement'] < 300)
& (df.index.str.contains('ford')
| df.index.str.contains('datsun')),
['weight', 'origin']
]

In [ ]:
total = 0
for value in [3,2,19]:
total += value
print('Total is: {0}'.format(total))

In [ ]:
total = 0
for value in [2,3,19]:
for weight in [3, 2, 1]:
total += value * weight
print('Total is: {0}'.format(total))

In [ ]:
total = 0
for value, weight in zip([2,3,19],
[0.2,0.3,0.5]):
total += weight * value
print('Weighted average is: {0}'.format(total))

In [ ]:
rng = np.random.default_rng(1)
A = rng.standard_normal((127, 5))
M = rng.choice([0, np.nan], p=[0.8,0.2], size=A.shape)
A += M
D = pd.DataFrame(A, columns=['food',
'bar',
'pickle',
'snack',
'popcorn'])
D[:3]

In [ ]:
for col in D.columns:
template = 'Column "{0}" has {1:.2%} missing values'
print(template.format(col,
np.isnan(D[col]).mean()))

In [ ]:
fig, ax = subplots(figsize=(8, 8))
ax.plot(horsepower , mpg, 'o');

In [ ]:
fig, ax = subplots(figsize=(8, 8))
ax.plot(Auto['horsepower'], Auto['mpg'], 'o');

In [ ]:
ax = Auto.plot.scatter('horsepower', 'mpg');
ax.set_title('Horsepower vs. MPG')

In [ ]:
fig = ax.figure
fig.savefig('horsepower_mpg.png');

In [ ]:
fig, axes = subplots(ncols=3, figsize=(15, 5))
Auto.plot.scatter('horsepower', 'mpg', ax=axes[1]);

In [ ]:
Auto.cylinders = pd.Series(Auto.cylinders, dtype='category')
Auto.cylinders.dtype

In [ ]:
fig, ax = subplots(figsize=(8, 8))
Auto.boxplot('mpg', by='cylinders', ax=ax);

In [ ]:
fig, ax = subplots(figsize=(8, 8))
Auto.hist('mpg', ax=ax);

In [ ]:
fig, ax = subplots(figsize=(8, 8))
Auto.hist('mpg', color='red', bins=12, ax=ax);

In [ ]:
pd.plotting.scatter_matrix(Auto);

In [ ]:
pd.plotting.scatter_matrix(Auto[['mpg',
'displacement',
'weight']]);

In [ ]:
Auto[['mpg', 'weight']].describe()

In [ ]:
Auto['cylinders'].describe()
Auto['mpg'].describe()

### Linear Regression

In [ ]:
import numpy as np
import pandas as pd
from matplotlib.pyplot import subplots

In [ ]:
import statsmodels.api as sm

In [ ]:
from statsmodels.stats.outliers_influence \
import variance_inflation_factor as VIF
from statsmodels.stats.anova import anova_lm

In [ ]:
from ISLP import load_data
from ISLP.models import (ModelSpec as MS,
summarize,
poly)

In [ ]:
dir()

In [ ]:
A = np.array([3,5,11])
dir(A)

In [ ]:
A.sum()

In [ ]:
Boston = load_data("Boston")
Boston.columns

In [ ]:
X = pd.DataFrame({'intercept': np.ones(Boston.shape[0]),
'lstat': Boston['lstat']})
X[:4]

In [ ]:
y = Boston['medv']
model = sm.OLS(y, X)
results = model.fit()

In [ ]:
summarize(results)

In [ ]:
design = MS(['lstat'])
design = design.fit(Boston)
X = design.transform(Boston)
X[:4]


In [ ]:
design = MS(['lstat'])
X = design.fit_transform(Boston)
X[:4]


In [ ]:
results.summary()

In [ ]:
results.params

In [ ]:
new_df = pd.DataFrame({'lstat':[5, 10, 15]})
newX = design.transform(new_df)
newX

In [ ]:
new_predictions = results.get_prediction(newX);
new_predictions.predicted_mean

In [ ]:
new_predictions.conf_int(alpha=0.05)

In [ ]:
new_predictions.conf_int(obs=True, alpha=0.05)

In [ ]:
def abline(ax, b, m):
"Add a line with slope m and intercept b to ax"
xlim = ax.get_xlim()
ylim = [m * xlim[0] + b, m * xlim[1] + b]
ax.plot(xlim, ylim)

In [ ]:
def abline(ax, b, m, *args, **kwargs):
"Add a line with slope m and intercept b to ax"
xlim = ax.get_xlim()
ylim = [m * xlim[0] + b, m * xlim[1] + b]
ax.plot(xlim, ylim, *args, **kwargs)

In [ ]:
ax = Boston.plot.scatter('lstat', 'medv')
abline(ax,
results.params[0],
results.params[1],
'r--',
linewidth=3)

In [ ]:
ax = subplots(figsize=(8,8))[1]
ax.scatter(results.fittedvalues , results.resid)
ax.set_xlabel('Fitted value')
ax.set_ylabel('Residual')
ax.axhline(0, c='k', ls='--');

In [ ]:
infl = results.get_influence()
ax = subplots(figsize=(8,8))[1]
ax.scatter(np.arange(X.shape[0]), infl.hat_matrix_diag)
ax.set_xlabel('Index')
ax.set_ylabel('Leverage')
np.argmax(infl.hat_matrix_diag)

In [ ]:
X = MS(['lstat', 'age']).fit_transform(Boston)
model1 = sm.OLS(y, X)
results1 = model1.fit()
summarize(results1)

In [ ]:
terms = Boston.columns.drop('medv')
terms

In [ ]:
X = MS(terms).fit_transform(Boston)
model = sm.OLS(y, X)
results = model.fit()
summarize(results)

In [ ]:
minus_age = Boston.columns.drop(['medv', 'age'])
Xma = MS(minus_age).fit_transform(Boston)
model1 = sm.OLS(y, Xma)
summarize(model1.fit())

In [ ]:
vals = [VIF(X, i)
for i in range(1, X.shape[1])]
vif = pd.DataFrame({'vif':vals},
index=X.columns[1:])
vif

In [ ]:
vals = []
for i in range(1, X.values.shape[1]):
vals.append(VIF(X.values, i))

In [ ]:
X = MS(['lstat',
'age',
('lstat', 'age')]).fit_transform(Boston)
model2 = sm.OLS(y, X)
summarize(model2.fit())

In [ ]:
X = MS([poly('lstat', degree=2), 'age']).fit_transform(Boston)
model3 = sm.OLS(y, X)
results3 = model3.fit()
summarize(results3)

In [ ]:
anova_lm(results1, results3)

In [ ]:
ax = subplots(figsize=(8,8))[1]
ax.scatter(results3.fittedvalues , results3.resid)
ax.set_xlabel('Fitted value')
ax.set_ylabel('Residual')
ax.axhline(0, c='k', ls='--')

In [ ]:
Carseats = load_data('Carseats')
Carseats.columns

In [3]:
allvars = list(Carseats.columns.drop('Sales'))
y = Carseats['Sales']
final = allvars + [('Income', 'Advertising'),
('Price', 'Age')]
X = MS(final).fit_transform(Carseats)
model = sm.OLS(y, X)
summarize(model.fit())

NameError: name 'Carseats' is not defined